---
- name: Create directory
  file:
    dest: "{{ jolokia_parent_dir }}"
    mode: 0755
    state: directory

- name: Download the archive
  get_url:
    url: "{{ jolokia_url }}"
    dest: "{{ jolokia_parent_dir }}/{{ jolokia_file_name }}"
    timeout: 30

- name: Set permissions to the file
  file:
    path: "{{ jolokia_parent_dir }}/{{ jolokia_file_name }}"
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"

- name: Set up the jolokia config file
  template:
    src: jolokia_config.properties.j2
    dest: "{{ jolokia_parent_dir }}/jolokia_config.properties"
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: "0775"
  tags:
    - jolokia_agent

- name: "copy jolokia telegraf conf"
  template:
      src: "jolokia_telegraf.conf.j2"
      dest: "/etc/telegraf/telegraf.d/jolokia_telegraf.conf"
      mode: 0644
  when: jolokia_agent is defined 
  tags: jolokia_agent
  notify: restart telegraf


